apiVersion: v1
kind: Service
metadata:
  name: root-node
spec:
  ports:
  - port: 30080
    protocol: TCP
  selector:
    app: root-node
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-node
spec:
  selector:
    matchLabels:
      app: root-node
  template:
    metadata:
      labels:
        app: root-node
    spec:
      containers:
      - name: root-node
        image: elmanhasa/haskell-chain:latest
        imagePullPolicy: Always
        env:
        - name: CHAIN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: chainConfig
              name: root-node-config
        ports:
        - containerPort: 30080
      volumes:
        - name: logs
          emptyDir: {}
