tcpConfig:
  localPort: 3080
  peers:
    - ipAddress: "127.0.0.1"
      peerPort: 3081
mineConfig:
  mineDifficulty: 2
  mineFrequency: 60
dbConfig:
  dbFilePath: "/tmp/chainDb"
pollPeersConfig:
  pingPeersFrequency: 5
  checkPeersBlocksFrequency: 6
httpConfig:
  serverPort: 3080