tcpConfig:
  localPort: 3081
  peers:
    - ipAddress: "127.0.0.1"
      peerPort: 3080
mineConfig:
  mineDifficulty: 2
  mineFrequency: 60
dbConfig:
  dbFilePath: "/tmp/chainDb1"
pollPeersConfig:
  pingPeersFrequency: 5
  checkPeersBlocksFrequency: 6
httpConfig:
  serverPort: 3080